# Build settings
markdown: kramdown

# Theme settings
theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout

# Site settings
title: Ben Sprung-Keyser
description: "Economics PhD Student<br/> Harvard University"
baseurl: ""
url: ""

# Social settings
email: bsprungkeyser@g.harvard.edu
profile_photo_path: /assets/images/profile-photo.jpeg
