# Build settings
markdown: kramdown

# Theme settings
theme: jekyll-theme-cayman
remote_theme: fongandrew/hydeout

# Site settings
title: "Ben Sprung-Keyser"
name: "Ben <br/>Sprung-Keyser"
description: "Assistant Professor<br/> BEPP<br/> Wharton School<br/> University of Pennsylvania"
baseurl: ""
url: ""

# Social settings
cv_path: Sprung-Keyser_CV.pdf
email: bsprungk@wharton.upenn.edu
profile_photo_path: /assets/images/profile-photo.jpeg
twitter_username: bsprungkeyser

