# Build settings
markdown: kramdown

# Theme settings
theme: jekyll-theme-cayman
remote_theme: fongandrew/hydeout

# Site settings
title: "Ben Sprung-Keyser"
name: "Ben <br/>Sprung-Keyser"
description: "Postdoctoral Research Fellow<br/> Harvard University"
baseurl: ""
url: ""

# Social settings
email: bsprungkeyser@g.harvard.edu
profile_photo_path: /assets/images/profile-photo.jpeg
twitter_username: bsprungkeyser
cv: Sprung-Keyser_CV.pdf
