# Build settings
markdown: kramdown

# Theme settings
theme: jekyll-theme-hydeout
paginate: 5

# Site settings
title: Jeffrey Helt
description: "Computer Science PhD Student<br/>CS 314, Princeton University"
baseurl: ""
url: "https://www.cs.princeton.edu"

# Social settings
email: jhelt@cs.princeton.edu
phone: +1 203 246 5697
cv_path: /assets/cv.pdf
profile_photo_path: /assets/images/profile-photo.jpeg
